<?php
// test.php - Place this in data/www/example/cgi/test.php

// CGI must output headers first
header("Content-Type: text/html");

// Optional: Set status code
// header("Status: 200 OK");

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "<head>\n";
echo "    <title>CGI Test</title>\n";
echo "</head>\n";
echo "<body>\n";
echo "    <h1>CGI is Working!</h1>\n";
echo "    <h2>Environment Variables:</h2>\n";
echo "    <ul>\n";

// Display some CGI environment variables
$cgi_vars = array(
    'REQUEST_METHOD',
    'PATH_INFO',
    'QUERY_STRING',
    'CONTENT_TYPE',
    'CONTENT_LENGTH',
    'SERVER_SOFTWARE',
    'GATEWAY_INTERFACE',
    'SERVER_PROTOCOL',
    'SCRIPT_FILENAME',
    'SCRIPT_NAME'
);

foreach ($cgi_vars as $var) {
    $value = isset($_SERVER[$var]) ? $_SERVER[$var] : '(not set)';
    echo "        <li><strong>$var:</strong> $value</li>\n";
}

echo "    </ul>\n";

// Show POST data if any
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    echo "    <h2>POST Data:</h2>\n";
    echo "    <pre>";
    $post_data = file_get_contents('php://input');
    echo htmlspecialchars($post_data);
    echo "</pre>\n";
}

// Show GET parameters if any
if (!empty($_GET)) {
    echo "    <h2>GET Parameters:</h2>\n";
    echo "    <ul>\n";
    foreach ($_GET as $key => $value) {
        echo "        <li><strong>$key:</strong> " . htmlspecialchars($value) . "</li>\n";
    }
    echo "    </ul>\n";
}

echo "    <p><em>Generated by PHP CGI at " . date('Y-m-d H:i:s') . "</em></p>\n";
echo "</body>\n";
echo "</html>\n";
?>
